lugares = ['Canada', 'EUA', 'Europa', 'America Latina', 'America do Sul', 'Asia', 'Oriente', 'Australia', 'Africa']
print(lugares)
lugares_sorted = sorted(lugares)
print(lugares_sorted, '\n', lugares)
lugares_sorted = sorted(lugares, reverse=True)
print(lugares_sorted)
print(lugares)
lugares.reverse()
print(lugares)
lugares.reverse()
print(lugares)
lugares.sort()
print(lugares)
lugares.sort(reverse=True)
print(lugares)
